"""Add ai_usage_weekly

Revision ID: 7b4c497cb583
Revises: 
Create Date: 2025-11-23 21:34:10.200210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b4c497cb583'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_history_id'), table_name='campaign_history')
    op.drop_table('campaign_history')
    op.drop_index(op.f('ix_module_access_id'), table_name='module_access')
    op.drop_index(op.f('ix_module_access_module_name'), table_name='module_access')
    op.drop_table('module_access')
    op.drop_index(op.f('ix_content_usage_id'), table_name='content_usage')
    op.drop_table('content_usage')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_daily_usage_id'), table_name='daily_usage')
    op.drop_index(op.f('ix_daily_usage_user_id'), table_name='daily_usage')
    op.drop_table('daily_usage')
    op.drop_table('guide_sections')
    op.drop_index(op.f('ix_email_campaigns_id'), table_name='email_campaigns')
    op.drop_table('email_campaigns')
    op.drop_table('Automation')
    op.create_foreign_key(None, 'automations', 'users', ['user_id'], ['id'])
    op.drop_column('automations', 'is_active')
    op.add_column('campaigns', sa.Column('content', sa.Text(), nullable=True))
    op.drop_constraint(op.f('fk_campaigns_user'), 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'users', ['user_id'], ['id'])
    op.drop_column('campaigns', 'platform')
    op.drop_column('campaigns', 'ai_prompt')
    op.drop_column('campaigns', 'description')
    op.drop_column('campaigns', 'objective')
    op.drop_column('campaigns', 'ai_result')
    op.drop_column('campaigns', 'target_audience')
    op.add_column('content_history', sa.Column('type', sa.String(), nullable=False))
    op.add_column('content_history', sa.Column('input_prompt', sa.Text(), nullable=False))
    op.add_column('content_history', sa.Column('output_text', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'content_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('content_history', 'prompt')
    op.drop_column('content_history', 'generated_content')
    op.drop_column('content_history', 'content_type')
    op.add_column('guides', sa.Column('description', sa.String(length=500), nullable=True))
    op.drop_column('guides', 'content')
    op.add_column('ia_status', sa.Column('available_tokens', sa.Integer(), nullable=True))
    op.add_column('ia_status', sa.Column('used_tokens', sa.Integer(), nullable=True))
    op.alter_column('ia_status', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('ia_status', 'message')
    op.alter_column('library_items', 'file_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_constraint(op.f('fk_libraryitems_user'), 'library_items', type_='foreignkey')
    op.create_foreign_key(None, 'library_items', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'sales_pages', 'users', ['user_id'], ['id'])
    op.drop_column('sales_pages', 'blocks')
    op.alter_column('social_posts', 'reseau',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('social_posts', 'contenu',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5000),
               nullable=False)
    op.alter_column('social_posts', 'date_programmee',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_social_posts_id'), 'social_posts', ['id'], unique=False)
    op.drop_constraint(op.f('social_posts_user_id_fkey'), 'social_posts', type_='foreignkey')
    op.create_foreign_key(None, 'social_posts', 'users', ['user_id'], ['id'])
    op.drop_column('social_posts', 'updated_at')
    op.add_column('users', sa.Column('ai_usage_weekly', sa.Float(), nullable=False))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'essential'::character varying"))
    op.alter_column('users', 'ai_usage_limit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               nullable=False,
               existing_server_default=sa.text('15'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'ai_usage_limit',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('15'))
    op.alter_column('users', 'plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'essential'::character varying"))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'ai_usage_weekly')
    op.add_column('social_posts', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'social_posts', type_='foreignkey')
    op.create_foreign_key(op.f('social_posts_user_id_fkey'), 'social_posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_social_posts_id'), table_name='social_posts')
    op.alter_column('social_posts', 'date_programmee',
               existing_type=sa.String(length=255),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('social_posts', 'contenu',
               existing_type=sa.String(length=5000),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('social_posts', 'reseau',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('sales_pages', sa.Column('blocks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sales_pages', type_='foreignkey')
    op.drop_constraint(None, 'library_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_libraryitems_user'), 'library_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('library_items', 'file_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.add_column('ia_status', sa.Column('message', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('ia_status', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('ia_status', 'used_tokens')
    op.drop_column('ia_status', 'available_tokens')
    op.add_column('guides', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('guides', 'description')
    op.add_column('content_history', sa.Column('content_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('content_history', sa.Column('generated_content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('content_history', sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'content_history', type_='foreignkey')
    op.drop_column('content_history', 'output_text')
    op.drop_column('content_history', 'input_prompt')
    op.drop_column('content_history', 'type')
    op.add_column('campaigns', sa.Column('target_audience', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('ai_result', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('objective', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('campaigns', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('ai_prompt', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('campaigns', sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key(op.f('fk_campaigns_user'), 'campaigns', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('campaigns', 'content')
    op.add_column('automations', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'automations', type_='foreignkey')
    op.create_table('Automation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Automation_pkey'))
    )
    op.create_table('email_campaigns',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model_used', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('email_campaigns_pkey'))
    )
    op.create_index(op.f('ix_email_campaigns_id'), 'email_campaigns', ['id'], unique=False)
    op.create_table('guide_sections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('guide_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['guide_id'], ['guides.id'], name=op.f('guide_sections_guide_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('guide_sections_pkey'))
    )
    op.create_table('daily_usage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('email_generations', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_usage_pkey'))
    )
    op.create_index(op.f('ix_daily_usage_user_id'), 'daily_usage', ['user_id'], unique=False)
    op.create_index(op.f('ix_daily_usage_id'), 'daily_usage', ['id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('features', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('plans_pkey')),
    sa.UniqueConstraint('name', name=op.f('plans_name_key'))
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_table('content_usage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('credits_used', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('content_usage_pkey'))
    )
    op.create_index(op.f('ix_content_usage_id'), 'content_usage', ['id'], unique=False)
    op.create_table('module_access',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('module_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('free_access', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('starter_access', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('premium_access', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('module_access_pkey'))
    )
    op.create_index(op.f('ix_module_access_module_name'), 'module_access', ['module_name'], unique=True)
    op.create_index(op.f('ix_module_access_id'), 'module_access', ['id'], unique=False)
    op.create_table('campaign_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('detail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('campaign_history_campaign_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('campaign_history_pkey'))
    )
    op.create_index(op.f('ix_campaign_history_id'), 'campaign_history', ['id'], unique=False)
    # ### end Alembic commands ###
